"""initial schema

Revision ID: 09462d11fffe
Revises:
Create Date: 2026-10-08 22:49:27.910220

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "09462d11fffe"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statsbomb_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country_name", sa.String(length=255), nullable=True),
        sa.Column("gender", sa.String(length=32), nullable=True),
        sa.Column("format", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
    )
    op.create_index(
        op.f("ix_competitions_statsbomb_id"), "competitions", ["statsbomb_id"], unique=True
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statsbomb_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=True),
        sa.Column("country_name", sa.String(length=255), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("position_name", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_index(op.f("ix_players_name"), "players", ["name"], unique=False)
    op.create_index(op.f("ix_players_statsbomb_id"), "players", ["statsbomb_id"], unique=True)
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statsbomb_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("gender", sa.String(length=32), nullable=True),
        sa.Column("country_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_index(op.f("ix_teams_statsbomb_id"), "teams", ["statsbomb_id"], unique=True)
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("statsbomb_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_seasons_competition_id_competitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint(
            "competition_id", "statsbomb_id", name=op.f("uq_seasons_competition_id_statsbomb_id")
        ),
    )
    op.create_index(op.f("ix_seasons_competition_id"), "seasons", ["competition_id"], unique=False)
    op.create_index(op.f("ix_seasons_statsbomb_id"), "seasons", ["statsbomb_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statsbomb_id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("match_date", sa.Date(), nullable=False),
        sa.Column("kick_off", sa.Time(), nullable=True),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("stage_name", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"], ["teams.id"], name=op.f("fk_matches_away_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_matches_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"], ["teams.id"], name=op.f("fk_matches_home_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.id"], name=op.f("fk_matches_season_id_seasons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    op.create_index(op.f("ix_matches_away_team_id"), "matches", ["away_team_id"], unique=False)
    op.create_index(
        "ix_matches_competition_id_season_id",
        "matches",
        ["competition_id", "season_id"],
        unique=False,
    )
    op.create_index(op.f("ix_matches_home_team_id"), "matches", ["home_team_id"], unique=False)
    op.create_index(op.f("ix_matches_match_date"), "matches", ["match_date"], unique=False)
    op.create_index(op.f("ix_matches_statsbomb_id"), "matches", ["statsbomb_id"], unique=True)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statsbomb_id", sa.String(length=36), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("index_in_match", sa.Integer(), nullable=False),
        sa.Column("period", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.Time(), nullable=True),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("second", sa.Integer(), nullable=True),
        sa.Column("type_name", sa.String(length=64), nullable=False),
        sa.Column("possession", sa.Integer(), nullable=True),
        sa.Column("possession_team_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("location_x", sa.Float(), nullable=True),
        sa.Column("location_y", sa.Float(), nullable=True),
        sa.Column("outcome_name", sa.String(length=64), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_events_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_events_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["possession_team_id"], ["teams.id"], name=op.f("fk_events_possession_team_id_teams")
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_events_team_id_teams")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint(
            "match_id", "index_in_match", name=op.f("uq_events_match_id_index_in_match")
        ),
    )
    op.create_index(op.f("ix_events_match_id"), "events", ["match_id"], unique=False)
    op.create_index(op.f("ix_events_player_id"), "events", ["player_id"], unique=False)
    op.create_index(op.f("ix_events_statsbomb_id"), "events", ["statsbomb_id"], unique=True)
    op.create_index(op.f("ix_events_team_id"), "events", ["team_id"], unique=False)
    op.create_index(op.f("ix_events_type_name"), "events", ["type_name"], unique=False)
    op.create_table(
        "lineups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("jersey_number", sa.Integer(), nullable=True),
        sa.Column("position_name", sa.String(length=64), nullable=True),
        sa.Column("is_starter", sa.Boolean(), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_lineups_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_lineups_player_id_players")
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_lineups_team_id_teams")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lineups")),
        sa.UniqueConstraint(
            "match_id", "team_id", "player_id", name=op.f("uq_lineups_match_id_team_id_player_id")
        ),
    )
    op.create_index(op.f("ix_lineups_match_id"), "lineups", ["match_id"], unique=False)
    op.create_index(op.f("ix_lineups_player_id"), "lineups", ["player_id"], unique=False)
    op.create_index(op.f("ix_lineups_team_id"), "lineups", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lineups_team_id"), table_name="lineups")
    op.drop_index(op.f("ix_lineups_player_id"), table_name="lineups")
    op.drop_index(op.f("ix_lineups_match_id"), table_name="lineups")
    op.drop_table("lineups")
    op.drop_index(op.f("ix_events_type_name"), table_name="events")
    op.drop_index(op.f("ix_events_team_id"), table_name="events")
    op.drop_index(op.f("ix_events_statsbomb_id"), table_name="events")
    op.drop_index(op.f("ix_events_player_id"), table_name="events")
    op.drop_index(op.f("ix_events_match_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_matches_statsbomb_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_match_date"), table_name="matches")
    op.drop_index(op.f("ix_matches_home_team_id"), table_name="matches")
    op.drop_index("ix_matches_competition_id_season_id", table_name="matches")
    op.drop_index(op.f("ix_matches_away_team_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_seasons_statsbomb_id"), table_name="seasons")
    op.drop_index(op.f("ix_seasons_competition_id"), table_name="seasons")
    op.drop_table("seasons")
    op.drop_index(op.f("ix_teams_statsbomb_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_players_statsbomb_id"), table_name="players")
    op.drop_index(op.f("ix_players_name"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_competitions_statsbomb_id"), table_name="competitions")
    op.drop_table("competitions")
    # ### end Alembic commands ###
